## AI - Assignment 3

There are three questions that cover three chapters in RL study. 

Due date: March 29, 2021.


### Question 1 (5 points)
This question (Exercise 3.14 at page 60) is about the Bellman equation given at page 59 of the text book. "The Bellman equation Eq.(3.14), at page 59, must hold for each state for the value function $v_{\pi}$ shown in Figure 3.2 (right) of Example 3.5. Show numerically that this equation holds for the center state, valued at +0.7, with respect to its four neighboring states, valued at +2.3, +0.4, and 0.7".

This question asks you to verify the Bellman equation to check that at the center state the $v_{\pi} \approx 0.7$.

In order to get the mark of this question, you must list the detail of Bellman's equation, not just Bellman's equation result, which is $v_{\pi} \approx 0.7$.

Hint: use Bellman equation Eq.(3.14) to check the four actions (west, east, south, and north).

Solution:
    
$$ \pi(s, a= n) \sum_{s'} P_{s, s'}^{a=n} (R_{s,s'}^{a=n} + \gamma V^{\pi}(s')) + \\
    \pi(s, a= e) \sum_{s'} P_{s, s'}^{a=e} (R_{s,s'}^{a=e} + \gamma V^{\pi}(s')) + \\
    \pi(s, a= s) \sum_{s'} P_{s, s'}^{a=s} (R_{s,s'}^{a=s} + \gamma V^{\pi}(s')) + \\
    \pi(s, a= w) \sum_{s'} P_{s, s'}^{a=w} (R_{s,s'}^{a=w} + \gamma V^{\pi}(s'))  \\ 
    = \frac{1}{4} (R_{s,s'}^{a=n} + \gamma V^{\pi}(s')) + \frac{1}{4} (R_{s,s'}^{a=e} + \gamma V^{\pi}(s')) + \\
    \frac{1}{4} (R_{s,s'}^{a=s} + \gamma V^{\pi}(s')) + \frac{1}{4} (R_{s,s'}^{a=w} + \gamma V^{\pi}(s'))
    $$
    
Because $R=0$ for all states, above becomes:

$$ \frac{1}{4} ( \gamma V^{\pi}(s')) + \frac{1}{4} ( \gamma V^{\pi}(s')) + \\
    \frac{1}{4} ( \gamma V^{\pi}(s')) + \frac{1}{4} ( \gamma V^{\pi}(s')) \\
    = \frac{\gamma}{4} (2.3 + 0.4 -0.4 +0.7) \\
    = \frac{0.9}{4} \times 3.0 \approx 0.7
    $$

### Question 2 (5 points) 

This question is about the problem of policy prediction in dynamic programming algorithms. This is the only programming question. The question is given as:

Refer to the text book page 76, the example 4.1, write a Python script to calculate the $v_k$ values in each state shown in the left column of the Figure 1 in page 77.

Here are variables and initial values that you need for your script. You may need implement two functions:
one for calculating action value based on given state; another is for policy evaluation (prediction). However, you are free to design your script. Following functions' definitation is only for your reference.

The output of your script shall look like this:




In [4]:
import numpy as np
import matplotlib.pyplot as plt
import random

gamma = 1 # discounting rate
rewardSize = -1
gridSize = 4
terminationStates = [[0,0], [gridSize-1, gridSize-1]]
actions = ['left', 'right', 'up','down']
numIterations = 1000

In [2]:
# TODO:
def actionValue(state, action):
    if state in terminationStates:
        return state, 0
    reward = rewardSize
    newState = np.array(state)
    if action == 'left':
        newState = newState + np.array([-1,0])
    if action == 'right':
        newState = newState + np.array([1,0])
    if action == 'up':
        newState = newState + np.array([0,1])
    if action == 'down':
        newState = newState + np.array([0, -1])
    
    if -1 in newState or 4 in newState:
        newState = state
    return newState, reward

In [8]:
# TODO: policy evaluation
def policyEval():
    deltas = []
    pi_as = 1/len(actions)
    valueMap = np.zeros((gridSize, gridSize))
    states = [[i, j] for i in range(gridSize) for j in range(gridSize)]
    for i in range(numIterations):
        copyValueMap = np.copy(valueMap)
        deltaState = []
        for state in states:
            weightedRewards = 0
            for action in actions:
                newState, reward = actionValue(state, action)
                weightedRewards += pi_as * (reward + (gamma*valueMap[newState[0], newState[1]]))
            deltaState.append(np.abs(copyValueMap[state[0], state[1]] - weightedRewards))
            copyValueMap[state[0], state[1]] = weightedRewards
        deltas.append(deltaState)
        valueMap = copyValueMap
        if i in [0,1,2,9, 99, numIterations-1]:
            print("Iteration {}".format(i+1))
            print(valueMap)
            print("")

In [9]:
policyEval()

Iteration 1
[[ 0. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1.  0.]]

Iteration 2
[[ 0.   -1.75 -2.   -2.  ]
 [-1.75 -2.   -2.   -2.  ]
 [-2.   -2.   -2.   -1.75]
 [-2.   -2.   -1.75  0.  ]]

Iteration 3
[[ 0.     -2.4375 -2.9375 -3.    ]
 [-2.4375 -2.875  -3.     -2.9375]
 [-2.9375 -3.     -2.875  -2.4375]
 [-3.     -2.9375 -2.4375  0.    ]]

Iteration 10
[[ 0.         -6.13796997 -8.35235596 -8.96731567]
 [-6.13796997 -7.73739624 -8.42782593 -8.35235596]
 [-8.35235596 -8.42782593 -7.73739624 -6.13796997]
 [-8.96731567 -8.35235596 -6.13796997  0.        ]]

Iteration 100
[[  0.         -13.94260509 -19.91495107 -21.90482522]
 [-13.94260509 -17.92507693 -19.91551999 -19.91495107]
 [-19.91495107 -19.91551999 -17.92507693 -13.94260509]
 [-21.90482522 -19.91495107 -13.94260509   0.        ]]

Iteration 1000
[[  0. -14. -20. -22.]
 [-14. -18. -20. -20.]
 [-20. -20. -18. -14.]
 [-22. -20. -14.   0.]]



### Question 3. 

This question is about the Monte Carlo Methods on-policy and off-policy approaches. It is the Exercise 5.5 of the text book.

"Exercise 5.5 Consider an MDP with a single nonterminal state and a single action that transitions back to the nonterminal state with probability p and transitions to the terminal state with probability 1 - p. Let the reward be +1 on all transitions, and let $\gamma=1$. Suppose you observe one episode that lasts 10 steps, with a return of 10. What are the first-visit and every-visit estimators of the value of the nonterminal state?"

Hint: the first-visit means run the first episode, and every-visit means after the 10 episodes.

Solution:
    
$$ G \leftarrow \gamma G + R_{t+1} $$

$$ V(s) = \frac{\sum_{t \in J(s)} \rho_{t:T(t)-1} G_t}{|J(s)|} $$,

while, in this case, $|J(s)|=10$.

For the sirst-visit, $\rho_{t:T(t)-1}=1$, then the first-visit $$V(s) = \frac{10 + 10 + ... + 10}{10} = 10$$.

For the every-visit case: since $G_0 = 0 $, $ \gamma = 1 $, $R=+1$, So, we have:

$$ G_1 = \gamma G_0 + R_{0+1} = 1 $$,
$$ G_2 = \gamma G_1 + R_{1+1} = 2 $$,

...

$$ G_10 = \gamma G_9 + R_{9+1} = 10 $$,

So, we have:

$$ V(s) = \frac{(1+2+3+4+5+6+7+8+9+10)}{10} = 5.5 $$.